---
- name: Download cryosparc_master.
  ansible.builtin.get_url:
    url: "https://get.cryosparc.com/download/master-latest/{{ license }}"
    dest: "{{ cryosparc_user_home }}/cryosparc_master.tar.gz"
  become: yes
  become_user: "{{ cryosparc_user_name }}"
  when: (standalone or master) and install_from_download
  retries: 3

- name: Download cryosparc_worker.
  ansible.builtin.get_url:
    url: "https://get.cryosparc.com/download/worker-latest/{{ license }}"
    dest: "{{ cryosparc_user_home }}/cryosparc_worker.tar.gz"
  become: yes
  become_user: "{{ cryosparc_user_name }}"
  when: (worker or standalone) and install_from_download
  retries: 3

- name: Extract cryosparc_master.
  ansible.builtin.unarchive:
    src: "{{ cryosparc_user_home }}/cryosparc_master.tar.gz"
    dest: "{{ cryosparc_user_home }}"
  become: yes
  become_user: "{{ cryosparc_user_name }}"
  when: (standalone or master) and install_from_download

- name: Extract cryosparc_worker.
  ansible.builtin.unarchive:
    src: "{{ cryosparc_user_home }}/cryosparc_worker.tar.gz"
    dest: "{{ cryosparc_user_home }}"
  become: yes
  become_user: "{{ cryosparc_user_name }}"
  when: (worker or standalone) and install_from_download
