---
- name: Install cryosparc_master.
  ansible.builtin.shell:
    cmd: "./install.sh --license {{ license }} --hostname {{ ansible_hostname }} --dbpath {{ database_path }} --port {{ cryosparc_port }} --yes"
    chdir: "{{ cryosparc_user_home }}/cryosparc_master"
  become: yes
  become_user: "{{ crysoaprc_user_name }}"
  when: master

- name: Install cryosparc standalone.
  ansible.builtin.shell:
    cmd: "{{ item.command }}"
    chdir: "{{ cryosparc_user_home }}/cryosparc_master"
  with_items:
    - {
        command: "./install.sh --license {{ license }} --worker_path {{ cryosparc_user_home }}/cryosparc_worker --cudapath {{ cuda_path }} --ssdpath {{ ssd_path }} --port {{ cryosparc_port }} --yes",
        ssd: true,
      }
    - {
        command: "./install.sh --license {{ license }} --worker_path {{ cryosparc_user_home }}/cryosparc_worker --cudapath {{ cuda_path }} --port {{ cryosparc_port }} --yes",
        ssd: false,
      }
  become: yes
  become_user: "{{ crysoaprc_user_name }}"
  when: standalone and item.ssd == ssd

- name: Install cryosparc_worker.
  ansible.builtin.shell:
    cmd: "./install.sh --license {{ license }} --cudapath {{ cuda_path }} --yes"
    chdir: "{{ cryosparc_user_home }}/cryosparc_worker"
  become: yes
  become_user: "{{ crysoaprc_user_name }}"
  when: worker

- name: Start cryosparc.
  ansible.builtin.shell:
    cmd: "./bin/cryosparccm start"
  become: yes
  become_user: "{{ crysoaprc_user_name }}"
  when: standalone or master

- name: Connect worker.
  ansible.builtin.shell:
    cmd: "{{ item.command }}"
    chdir: "{{ cryosparc_user_home }}/cryosparc_worker"
  become: yes
  become_user: "{{ crysoaprc_user_name }}"
  with_items:
    - {
        command: "./bin/cryosparcw connect --worker {{ ansible_hostname }} --master {{ cryosparc_master_hostname }} --port {{ cryosparc_port }} --ssdpath {{ ssd_path }} --lane {{ lane }} --newlane",
        ssd: true,
        newlane: true,
      }
    - {
        command: "./bin/cryosparcw connect --worker {{ ansible_hostname }} --master {{ cryosparc_master_hostname }} --port {{ cryosparc_port }} --nossd --lane {{ lane }} --newlane",
        ssd: false,
        newlane: true,
      }
    - {
        command: "./bin/cryosparcw connect --worker {{ ansible_hostname }} --master {{ cryosparc_master_hostname }} --port {{ cryosparc_port }} --ssdpath {{ ssd_path }} --lane {{ lane }}",
        ssd: true,
        newlane: false,
      }
    - {
        command: "./bin/cryosparcw connect --worker {{ ansible_hostname }} --master {{ cryosparc_master_hostname }} --port {{ cryosparc_port }} --nossd --lane {{ lane }}",
        ssd: false,
        newlane: false,
      }
  when: worker and worker_connect and item.ssd == ssd and item.newlane == new_lane

  # TODO add cluster, atleast slurm for now
