---
- name: Get public host key.
  ansible.builtin.shell: cat /etc/ssh/ssh_host_ecdsa_key.pub | awk '{ print $1 " " $2 }'
  register: public_key
  when: not cluster_install

- name: Insert host into known hosts of cryosparc master.
  ansible.builtin.shell: ANSIBLE_HOST_KEY_CHECKING=false ansible -i {{ cryosparc_master_hostname }}, --extra-vars "ansible_ssh_user={{ cryosparc_master_user }} ansible_ssh_pass={{ cryosparc_master_pw }}" -m known_hosts -a 'host={{ ansible_hostname }} key="{{ ansible_hostname }},{{ ansible_default_ipv4.address }} {{ public_key.stdout }}"' all
  when: worker and not cluster_install
