---
- name: Add cryosparcuser group
  ansible.builtin.group:
    name: "{{ cryosparc_group_name }}"
    gid: "{{ cryosparc_group_gid }}"
    state: present
    system: false

- name: Add cryosparcuser user
  ansible.builtin.user:
    name: "{{ crysoaprc_user_name }}"
    uid: "{{ cryosparc_user_uid }}"
    group: "{{ cryosparc_group_name }}"
    create_home: true
    home: "{{ cryosparc_user_home }}"
    shell: "/bin/bash "
    state: present
    system: false
    generate_ssh_key: true

- name: Create .ssh folder for cryosparcuser
  ansible.builtin.file:
    path: "{{ cryosparc_user_home }}/.ssh"
    state: directory
    owner: "{{ crysoaprc_user_name }}"
    group: "{{ cryosparc_group_name }}"
    mode: 0700

- name: Get public host key.
  ansible.builtin.shell: cat /etc/ssh/ssh_host_ecdsa_key.pub | awk '{ print $1 " " $2 }'
  register: public_key

- name: Insert host into known hosts of cryosparc master.
  ansible.builtin.shell: ANSIBLE_HOST_KEY_CHECKING=false ansible -i {{ cryosparc_master_hostname }}, --extra-vars "ansible_ssh_user={{ cryosparc_master_user }} ansible_ssh_pass={{ cryosparc_master_pw }}" -m known_hosts -a 'host={{ ansible_hostname }} key="{{ ansible_hostname }},{{ ansible_default_ipv4.address }} {{ public_key.stdout }}"' all
  when: worker

- name: Fetch public ssh key for cryosparcuser from cryosparc master.
  ansible.builtin.shell: ANSIBLE_HOST_KEY_CHECKING=false ansible -i {{ cryosparc_master_hostname }}, --extra-vars "ansible_ssh_user={{ cryosparc_master_user }} ansible_ssh_pass={{ cryosparc_master_pw }}" -m fetch -a "src={{ cryosparc_master_sshkey }} dest={{ cryosparc_user_home }}/.ssh/authorized_keys flat=yes" all
  when: worker

- name: Create .ssh/authorized_keys file for cryosparcuser
  ansible.builtin.file:
    path: "{{ cryosparc_user_home }}/.ssh/authorized_keys"
    state: touch
    owner: "{{ crysoaprc_user_name }}"
    group: "{{ cryosparc_group_name }}"
    mode: 0600
